# Generated by Django 5.1.7 on 2025-03-25 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copropiedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apartamento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='AccesoVisitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitante', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('autorizado', 'Autorizado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Residente',
        ),
    ]
