# Generated by Django 5.1.7 on 2025-03-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copropiedades', '0002_usuario_apartamento_accesovisitante_delete_residente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesovisitante',
            old_name='visitante',
            new_name='visitante_nombre',
        ),
        migrations.AddField(
            model_name='accesovisitante',
            name='apartamento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
