# Generated by Django 5.1.7 on 2025-03-26 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copropiedades', '0003_rename_visitante_accesovisitante_visitante_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesovisitante',
            name='apartamento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='apartamento',
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('copropiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copropiedades.copropiedad')),
            ],
        ),
        migrations.AddField(
            model_name='accesovisitante',
            name='residencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='copropiedades.residencia'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='residencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='copropiedades.residencia'),
        ),
    ]
